version: '2.4'
services:
  ubt20:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:ubt20-v6
    restart: unless-stopped
    shm_size: 1g
    privileged: true #
    ports:
      - "11081:10081"
      - "11089:10089"
      - "11022:10022"
    volumes: 
      - /_ext:/_ext
      - /:/mnt  

  deb10:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:deb10t-v4-slim
    restart: unless-stopped
    shm_size: 1g
    ports:
      - "12081:10081"
      - "12089:10089"
      - "12022:10022"      
    volumes: 
      - /_ext:/_ext
      - /:/mnt  

  core:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:core-v4-slim
    restart: unless-stopped
    shm_size: 1g
    privileged: true #
    ports:
      - "13081:10081"
      - "13089:10089"
      - "13022:10022"
    cap_add:
      - SYS_BOOT 
      - SYS_ADMIN         
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup 
      - /_ext:/_ext
      - /:/mnt  

  deb9:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:full
    restart: unless-stopped
    shm_size: 1g
    ports:
      - "14081:10081"
      - "14089:10089"
      - "14022:10022"
    environment:
      - SSH_PASS=headless
      - VNC_PASS=headless
      - VNC_PASS_RO=View123
      - TZ=Asia/Shanghai
      - L=zh_CN
    volumes: 
      - /_ext:/_ext
      - /:/mnt      
