version: '2.4'
services:
  x11:
    image: infrastlabs/docker-headless:slim
    restart: unless-stopped
    environment:
      - SSH_PASS=headless
      - VNC_PASS=headless
      - VNC_PASS_RO=View123
      - VNC_OFFSET=30
      - VNC_LIMIT=4
    #network_mode: bridge
    ports:
      - "10081:10081" #novnc
      - "10089:10089" #rdp
      - "10082:10082" #audio
      - "10022:10022" #ssh
    volumes:
      - /_ext:/_ext
      - /:/mnt

  de-mate:
    image: infrastlabs/docker-headless
    command: xfce4-session
    user: headless
    # image: x11docker/mate
    restart: unless-stopped
    depends_on:
      - x11
    environment:
      - DISPLAY=x11:31
      - PULSE_SERVER=tcp:x11:4731
    volumes:
      - /_ext:/_ext
      - /:/mnt

  de-xfce:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:xfce-deb11-v2
    restart: always
    depends_on:
      - x11
    environment:
      - DISPLAY=x11:32
      - PULSE_SERVER=tcp:x11:4732
    volumes:
      - /_ext:/_ext
      - /:/mnt

  de-plasma:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/kde-vnc:bionic
    restart: always
    depends_on:
      - x11
    environment:
      - DISPLAY=x11:33
      - PULSE_SERVER=tcp:x11:4733
    volumes:
      - /_ext:/_ext
      - /:/mnt

  de-headless:
    image: infrastlabs/docker-headless
    #command: startxfce4
    command: xfce4-session
    user: headless
    restart: unless-stopped
    depends_on:
      - x11
    environment:
      - DISPLAY=x11:34
      - PULSE_SERVER=tcp:x11:4734
    volumes:
      - /_ext:/_ext
      - /:/mnt
