version: '2.4'
services:
  x11:
    image: infrastlabs/docker-headless:slim
    restart: unless-stopped
    environment:
      - SSH_PASS=headless
      - VNC_PASS=headless
      - VNC_PASS_RO=View123
      - VNC_OFFSET=30
      - VNC_LIMIT=7
    #network_mode: bridge
    ports:
      - "10081:10081" #novnc
      - "10089:10089" #rdp
      - "10082:10082" #audio
      - "10022:10022" #ssh
    volumes:
      - /_ext:/_ext
      - /:/mnt

  de-mate:
    # image: x11docker/mate
    image: infrastlabs/docker-headless
    #command: bash -c "export HOME=/home/headless USER=headless SHELL=/bin/bash TERM=xterm; xfce4-session"
    #command: bash -c "export SHELL=/bin/bash ; xfce4-session"
    command: xfce4-session
    user: headless
    restart: unless-stopped
    depends_on:
      - x11
    environment:
      - SHELL=/bin/bash
      - DISPLAY=x11:31
      - PULSE_SERVER=tcp:x11:4731
    volumes:
      - /_ext:/_ext
      - /:/mnt

  de-xfce:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:xfce-deb11-v2
    restart: always
    depends_on:
      - x11
    environment:
      - DISPLAY=x11:32
      - PULSE_SERVER=tcp:x11:4732
    volumes:
      - /_ext:/_ext
      - /:/mnt

  de-plasma:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/kde-vnc:bionic
    restart: always
    depends_on:
      - x11
    environment:
      - DISPLAY=x11:33
      - PULSE_SERVER=tcp:x11:4733
    volumes:
      - /_ext:/_ext
      - /:/mnt

  de-gnome:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-ubuntu-desktop-vnc:gnome3
    restart: unless-stopped
    depends_on:
      - x11
    environment:
      - DISPLAY=x11:34
      - PULSE_SERVER=tcp:x11:4734
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup 
      - /_ext:/_ext
      - /:/mnt      
    cap_add:
      - SYS_BOOT 
      - SYS_ADMIN      

  de-cinnamon:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-ubuntu-desktop-vnc:cinnamon3
    restart: unless-stopped
    depends_on:
      - x11
    environment:
      - DISPLAY=x11:35
      - PULSE_SERVER=tcp:x11:4735
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup 
      - /_ext:/_ext
      - /:/mnt      
    cap_add:
      - SYS_BOOT 
      - SYS_ADMIN

  de-headless:
    image: infrastlabs/docker-headless
    #command: startxfce4
    command: xfce4-session
    user: headless
    restart: unless-stopped
    depends_on:
      - x11
    environment:
      - DISPLAY=x11:36
      - PULSE_SERVER=tcp:x11:4736
    volumes:
      - /_ext:/_ext
      - /:/mnt
