version: '2.4'
services:
  xserver:
    # latest, slim, full
    image: infrastlabs/docker-headless:slim
    container_name: xserver
    restart: unless-stopped
    environment:
      - SSH_PASS=headless
      - VNC_PASS=headless
      - VNC_PASS_RO=View123
      - VNC_OFFSET=20
      - VNC_LIMIT=3
    network_mode: host
  de1:
    # xfce-deb11-v2 xfce-ubt2004-v2
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:xfce-ubt2004-v2
    restart: unless-stopped
    network_mode: host
    environment:
      - DISPLAY=:21
      - PULSE_SERVER=tcp:localhost:4721
    volumes:
      - /_ext:/_ext
      - /opt:/opt
      - /:/mnt