##Prod: Change Password############################
#  SSH_PASS=ChangeMe  VNC_PASS=ChangeMe2  VNC_PASS_RO=ChangeMe3
#  echo "headless:$SSH_PASS" |sudo chpasswd
#  echo -e "$VNC_PASS\n$VNC_PASS\ny\n$VNC_PASS_RO\n$VNC_PASS_RO"  |sudo vncpasswd /etc/xrdp/vnc_pass; sudo chmod 644 /etc/xrdp/vnc_pass
###################################################
version: '2.4'
services:
  latest:
    image: infrastlabs/docker-headless:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "supervisorctl status |grep -v 'RUNNING' && exit 1 || exit 0 "]
    shm_size: 1g
    privileged: true
    network_mode: host
    environment:
      - SSH_PASS=headless
      - VNC_PASS=headless
      - VNC_PASS_RO=View123
      - VNC_OFFSET=20 #default 10
      - TZ=Asia/Shanghai
      - L=zh_CN
    volumes: 
      - /_ext:/_ext
      - /opt:/opt
      - /:/mnt  

  sogou:
    image: infrastlabs/docker-headless:sogou
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "supervisorctl status |grep -v 'RUNNING' && exit 1 || exit 0 "]
    shm_size: 1g
    privileged: true
    network_mode: host
    environment:
      - VNC_OFFSET=21  #5900+21
      - PORT_SSH=11022
      - PORT_VNC=11081
      - PORT_RDP=11089
    volumes: 
      - /_ext:/_ext
      - /opt:/opt
      - /:/mnt  

  core:
    image: infrastlabs/docker-headless:core
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "supervisorctl status |grep -v 'RUNNING' && exit 1 || exit 0 "]
    shm_size: 1g
    privileged: true
    network_mode: host
    environment:
      - VNC_OFFSET=22
      - PORT_SSH=12022
      - PORT_VNC=12081
      - PORT_RDP=12089
    volumes: 
      - /_ext:/_ext
      - /opt:/opt
      - /:/mnt      
