version: '2.2'
services:
  xserver:
    # box04, box04-slim, box04-full
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:latest
    restart: always
    environment:
      - VNC_RW=passwd!@#
      - VNC_RO=passwd
      # - VNC_OFFSET=0
      # - VNC_LIMIT=3
      - TZ=Asia/Shanghai
      - L=zh_CN
    volumes:
      - /_ext:/_ext
      - /opt:/opt
    ports:
      - "10089:10089"
      - "10081:10081"
      - "10022:10022"
      # - "6000-6009:6000-6009" #VNC: offset 0, limit 10;
      # - "4700-4709:4700-4709"
    # network_mode: host
    privileged: true
    shm_size: 1g
  # de-mate:
  #   image: x11docker/mate
  #   # command: mate-session
  #   restart: always
  #   links:
  #     - xserver
  #   environment:
  #     - DISPLAY=xserver:1
  #     - PULSE_SERVER=xserver:47001
