version: '2.2'
services:
  headless:
    # latest, slim, full
    image: infrastlabs/docker-headless:full
    container_name: headless
    restart: always
    environment:
      - SSH_PASS=headless
      - VNC_PASS=headless
      - VNC_PASS_RO=View123
      - VNC_CERT=
      # - VNC_OFFSET=0
      # - VNC_LIMIT=3
      - TZ=Asia/Shanghai
      - L=zh_CN
    volumes:
      - /_ext:/_ext
      - /opt:/opt
      - /:/mnt
    # ports:
    #   - "10089:10089"
    #   - "10081:10081"
    #   - "10022:10022"
    #   # - "6000-6009:6000-6009" #VNC: offset 0, limit 10;
    #   # - "4700-4709:4700-4709"
    network_mode: host
    privileged: true
    shm_size: 1g
