version: '2.4'
services:
  # https://github.com/RavenKyu/docker-ubuntu-desktop-vnc
  ubuntu-20.04-desktop:
    # image: ubuntu-20.04-desktop-gnome:latest
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-ubuntu-desktop-vnc:lite1
    # command: tail -f /dev/null
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: ubuntu-desktop
    ports:
      - 5901:5901
      - 6080:6080
    # with systemd /bin/init
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup 
    cap_add:
      - SYS_BOOT 
      - SYS_ADMIN
    # 
    restart: unless-stopped
    network_mode: host
    # environment:
    #   - DISPLAY=:31
    #   - PULSE_SERVER=tcp:localhost:4731