version: '2.4'
services:
  x11:
    image: infrastlabs/docker-headless:slim
    restart: unless-stopped
    environment:
      - SSH_PASS=headless
      - VNC_PASS=headless
      - VNC_PASS_RO=View123
      - VNC_OFFSET=20
      - VNC_LIMIT=3
    network_mode: host
  de1:
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:xfce-deb11-v2
    restart: unless-stopped
    network_mode: host
    environment:
      - DISPLAY=:21
      - PULSE_SERVER=tcp:localhost:4721
